# File syntax : https://docs.docker.com/compose/compose-file/
# Global config, you can add your <ENV>.yml to override this one with -f option.

version: "3.6"

services:

  http:
    build: ./docker/nginx
    container_name: starter_nginx
    working_dir: /srv
    restart: on-failure
    depends_on:
      - web-stack

  web-stack:
    build: ./docker/web
    container_name: starter_web_stack
    working_dir: /srv
    restart: on-failure
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: starter_mariadb
    working_dir: /srv
    restart: on-failure
